# Generated by Django 4.2.1 on 2023-05-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('km', models.PositiveIntegerField()),
                ('engine', models.FloatField()),
                ('transmission', models.CharField(max_length=10)),
                ('fuel', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('searched_counter', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='cars.category')),
            ],
        ),
    ]
