# Generated by Django 4.2.1 on 2023-05-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_category_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='searched_counter',
        ),
    ]
